### ISSUE TITLE
PA review: User Authentication

### ISSUE THREAD

**Issue by Yzof** [Yzof/Dungeon-Diggur#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by Yzof** [comment]
@niartenyaw Finished with User Auth! Heres the link http://dungeon-diggur.herokuapp.com/

**Comment by Yzof** [comment]
@niartenyaw Got the styling and demo user working! Also, my dyno's are falling asleep(I think, the app is loading slower) how do I go about keeping them awake? Some quick googling didn't give me any satisfactory results

**Comment by niartenyaw** [comment]
Nice, looks great! Two small things

## Styling

- [ ] Still see that on `/signup`, the `Login` link isn't centered with the `signup` button
- [ ] The dropdown is out of line with the username

**Comment by niartenyaw** [comment]
And for the dyno, that's just a reality of hosting on a free site like heroku. The easiest way to eventually fix that (I'd recommend in the job search) is to pay a few bucks a month to keep it up. There are services that will ping your site at certain intervals, but heroku limits you to having a certain number of active hours per month so you have to be careful.
